### ISSUE TITLE
Behavior files with Multiple behaviors are not correctly parsed

### ISSUE THREAD

**Issue by manolo** [Polymer/hydrolysis#123]
When the file `paper-behaviors/paper-radio-button-behavior.html` is parsed 

```
<script>
  /** @polymerBehavior */
  Polymer.PaperRadioButtonInk = {
   ...
  };

  /** @polymerBehavior */
  Polymer.PaperRadioButtonBehavior = [
    Polymer.IronButtonState,
    Polymer.IronControlState,
    Polymer.PaperRadioButtonInk
  ];
</script>
```

It produces a result with just a behavior `'Polymer.PaperRadioButtonInk'`

```
{
 ...
  behaviors: 
   [ { type: 'behavior',
       ...
       is: 'Polymer.PaperRadioButtonInk',
       properties: [Object] } ]
 ...
}
```

But it **should** also include `Polymer.PaperRadioButtonBehavior` :

```
{
 ...
  behaviors: 
   [ { type: 'behavior',
       is: 'Polymer.PaperRadioButtonInk'} ,

     { type: 'behavior',
       is: 'Polymer.PaperRadioButtonBehavior' } ]
 ...
}
```

**Comment by atotic** [comment]
This is the funky new way we doc behaviors, to complement the funk of defining them. This is what you should do:
```
  /** @polymerBehavior Polymer.PaperButtonBehavior */
  Polymer.PaperButtonBehaviorImpl = {
}

  /** @polymerBehavior */
  Polymer.PaperButtonBehavior = [

Doc request for this is outstanding: : https://github.com/PolymerElements/style-guide/issues/6

**Comment by manolo** [comment]
Adding the real name does not fix anything, since nested behaviours are not considered in the output.

**Comment by atotic** [comment]
It works. I've just created a branch to demo the correct usage:
https://github.com/PolymerElements/paper-behaviors/tree/behaviorDocs

Another problem you have with documenting paper-behaviors is that we by default iron-component-page will only load whatever bower.json.main specifies, and follow local links from there. So, inky focus does not show up. I've made it appear by including inky-focus inside paper-button-behavior just to demonstrate that behaviors do show up.

**Comment by atotic** [comment]
Oops, there is a solution. You need to modify bower.json, and add inky to the list of main files.

**Comment by atotic** [comment]
Just committed it. The inky docs will not show up when  testing locally, but will in catalog.

**Comment by manolo** [comment]
Thanks it works for us. Is this fix going to be merged into master?.
Just as info we don't use hydrolysis to generate documentation but to analyze webcomponents and generate java code to use them by GWT developers.

**Comment by garlicnation** [comment]
The @manolo This change has been merged. Is it working for you?
