### ISSUE TITLE
Parsing Errors.

### ISSUE THREAD

**Issue by wintersandroid** [Polymer/hydrolysis#137]
This is happening to me on a yeoman scaffolded polymer project based off the starter..

I had added a line into analyser.js to see what file it fails on, but it is random..

```
[TypeError: Cannot read property 'end' of undefined]
/home/mathew/Development/sensor-net/sensor-net-web-app/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:230
  if (parsed.script) {
            ^
TypeError: Cannot read property 'script' of null
    at Analyzer._parseHTML (/home/mathew/Development/sensor-net/sensor-net-web-app/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:230:13)
    at Analyzer.<anonymous> (/home/mathew/Development/sensor-net/sensor-net-web-app/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/lib/analyzer.js:201:22)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by wintersandroid** [comment]
I have figured it out by putting each element into a clean project until it failed..

It might be a good case for better error messages..

Within a table I had

```
          <tr>
              <td class="label">Current</td>
              <td class="value" align="right">{{formatTheValue(dash_item.nodeSensor.recent_value,dash_item.sensor.type)}}</td>
            </td>
```

Where the <tr> was terminated with a typo </td>

Had me puzzled for a while..

**Comment by garlicnation** [comment]
The problem here was that the syntax was still valid enough for the parser to understand it. I should report the file being processed when an error occurs, however(This works well already for syntax errors in JS src).

**Comment by samccone** [comment]
:+1: yes plz jus.. just hit this

**Comment by samccone** [comment]
ref #143

**Comment by garlicnation** [comment]
Just pushed https://github.com/Polymer/hydrolysis/tree/malformedHTMLerrors.

I'm having trouble getting a test case that reproduces this. @samccone, do you have the input that caused an exception in analyzer._parseHTML?

**Comment by samccone** [comment]
yay here this will break it

```html
<dom-module id="foo">
</dom-module>
<script src="wow.js"><script>
```
