### ISSUE TITLE
Not support keyword 'super' reopened

### ISSUE THREAD

**Issue by himulawang** [Polymer/hydrolysis#141]
https://github.com/Polymer/hydrolysis/issues/129

Still has this problem.

**Comment by justinfagnani** [comment]
Here's a minimal repro:

```html
<!DOCTYPE html>
<html>
  <head>
    <script>
    class A {
      constructor() {
        super();
      }
    }
    </script>
  </head>
</html>
```

**Comment by justinfagnani** [comment]
"Super" node support should have been added to espree  in: https://github.com/eslint/espree/issues/115
