### ISSUE TITLE
Last line of previous documentation is assigned as documentation for next block.

### ISSUE THREAD

**Issue by ktiedt** [Polymer/hydrolysis#156]
![image](https://cloud.githubusercontent.com/assets/97242/9318388/14611ace-44f8-11e5-9bd4-55ad4655c8f8.png)

Have not played with this yet to see if this is specific to the next method being an Observer or not, but the comment from `currentMonthChanged` is completely ignored

**Comment by garlicnation** [comment]
For hydrolysis to find comments, they need to be written as follows:
```
/**
This comment style
*/
beforeTheMethodName
```

**Comment by ktiedt** [comment]
If that is the case, why is it picking up the comment from the detached method before it? There is at least one problem here, even if it was not what I expected right? :)

**Comment by garlicnation** [comment]
We're pretty limited in how well we can handle this, since comment information is stripped from the AST we're provided. If there were a way to coerce espree into producing a CST, we could vastly improve the cases we can handle.
