### ISSUE TITLE
Provide way to skip ENONENT resources instead of errroing out.

### ISSUE THREAD

**Issue by ebidel** [Polymer/hydrolysis#186]
Say I have a valid API endpoint in my app: `<script src="/api/endpoint.json"></script>`
Hydrolysys will error out but it's a valid URL in my app. 

It would be nice to provide a config option to just ignore non-found files instead of erroring out.

Currently, running the `metadataTree` API here:
https://github.com/GoogleChrome/http2-push-manifest/blob/master/lib/listresources.js#L119

**Comment by garlicnation** [comment]
This is supported by existing functionality. After creating your FS and XHR resolvers, create a NoopResolver for the URLs you want to exclude like this:
```javascript
loader.addResolver(new NoopResolver(/\/api\/endpoint\.json/);
```

**Comment by garlicnation** [comment]
Note that if you use the [Analyzer.analyze](https://github.com/Polymer/hydrolysis/blob/master/API.md#hydrolysis.Analyzer.analyze) API, you can handle this with `options.filter`.

**Comment by ebidel** [comment]
As discussed on chat, this is for a tool that won't know the URLs ahead of time. However, @garlicnation promised me a gist extending FSResolver :)

**Comment by ebidel** [comment]
Here's the magic: https://gist.github.com/garlicnation/82093eda74f5bc63b041
