### ISSUE TITLE
API: don't require chain of promises to access file content

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/hydrolysis#36]
Right now you have to chain Promises to get to the parsed content of an HTML file:

```
new Monomers(...).load(url).then(function(descriptor) {
  return descriptor.htmlLoaded;
}).then(function(document) {
  // do things
});
```

The value that `load(url)` resolves to could be provided synchronously, since its properties consist of a sync value (`html`) and three Promises. Then the above could be:

```
new Monomers(...).load(url).htmlLoaded.then(function(document) {
  // do things  
});
```

**Comment by garlicnation** [comment]
This has been fixed. Before `load resolves, `Analyzer.parsedDocuments` is populated with the parse5 AST of the loaded document.

```javascript
var a = new Analyzer(...).load(url).then(function(analyzedDocument) {
  var doc = a.parsedDocuments[analyzedDocument.href];
}
```
